In [1]:
import numpy as np

## Matrix Addition

In [8]:
mat1_add = np.random.randint(10,size=(3,3))
mat2_add = np.random.randint(20, size=(3,3))
print(mat1_add)
print(mat2_add)

[[3 4 8]
 [1 8 3]
 [4 0 9]]
[[16  9 16]
 [18 19  2]
 [ 4  3  2]]


In [9]:
sum = np.add(mat1_add,mat2_add)
print(sum)

[[19 13 24]
 [19 27  5]
 [ 8  3 11]]


# Matrix Subtraction

In [12]:
mat1_sub = np.random.randint(20, size=(5,5))
mat2_sub = np.random.randint(30, size=(5,5))
print(mat1_sub)
print(mat2_sub)

[[ 1 19  3  8  4]
 [ 7  7  1  4 15]
 [13  9  8  9  9]
 [15 14 10 14  0]
 [ 6 13 17  5  5]]
[[19 18 27 21 12]
 [ 7 23 15 26  3]
 [18  7 20 17 29]
 [18 19 24  2 24]
 [10 22 18 23 23]]


In [13]:
difference = np.subtract(mat1_sub,mat2_sub)
print(difference)

[[-18   1 -24 -13  -8]
 [  0 -16 -14 -22  12]
 [ -5   2 -12  -8 -20]
 [ -3  -5 -14  12 -24]
 [ -4  -9  -1 -18 -18]]


# Multiply Matrix by scaler

In [14]:
x = 5
y = np.random.randint(10, size=(5,5))
print(x)
print(y)

5
[[3 6 8 6 2]
 [7 6 9 9 8]
 [9 7 5 3 6]
 [4 5 6 2 8]
 [4 5 4 4 4]]


In [15]:
multiply = np.multiply(x,y)
print(multiply)

[[15 30 40 30 10]
 [35 30 45 45 40]
 [45 35 25 15 30]
 [20 25 30 10 40]
 [20 25 20 20 20]]


# Multiply of two Matrics

In [25]:
ma1 = np.random.randint(20, size=(10,10))
ma2 = np.random.randint(30, size=(10,10))
print(ma1)
print(             '                X'      )
print(ma2)

[[ 8  1 16  3 18  7 16  9  3 10]
 [15 17  7 12  6 15 15  6  4 11]
 [11  7 16  5 19  7 17 17 16 14]
 [ 3  9 19 10 11  7  4 11 19  3]
 [17  1 12 10  8  0  6 11  5 12]
 [ 8  5 12  9 14  7  6  4  8  9]
 [ 5 10 18 11  5 18  3 19  1 13]
 [ 9  5 11  5 17  1  6  8 16 16]
 [19  0 10 19 17  6 11 15 17  8]
 [15  7  7  3  4 11 13 11  4 19]]
                X
[[28 14  8  9  2  7 22 11  9 10]
 [ 4  5 25 29 29 19  5 22 10 22]
 [19 17 14 14  3 27 23 29 23 16]
 [ 6  0 19  5 20  8 13 18  1 27]
 [ 9 12 12  4 15 10  1  6  4 26]
 [ 5  9 21  6 12 16 15 26  4 20]
 [22  5 11 10  1 27  7  0  4 13]
 [11 17 23 28 27 12  2 17 26  2]
 [ 5  7 21 21 12 16  5  0 16  9]
 [11 17  8 16 13 25 11 25 10 22]]


In [26]:
product = np.dot(ma1,ma2)
print(product)

[[1323 1092 1259 1089  932 1661  966 1321  999 1520]
 [1359 1013 1733 1478 1422 1829 1221 1761  952 1901]
 [1671 1476 1983 1875 1592 2253 1221 1764 1552 1996]
 [1012  996 1704 1485 1341 1626  972 1472 1272 1539]
 [1250  999 1135 1097  938 1296 1014 1272  991 1271]
 [1002  879 1241 1012  998 1362  902 1267  837 1485]
 [1146 1214 1784 1561 1562 1787 1199 2141 1314 1717]
 [1145 1101 1385 1355 1185 1595  887 1282 1109 1563]
 [1599 1259 1870 1525 1499 1770 1282 1554 1298 1927]
 [1326 1114 1361 1359 1111 1689 1076 1548 1021 1466]]
