In [20]:
import numpy as np

# Creating Matrics Using Numpy

In [21]:
mat_1 = np.array([2,5,8])
mat_2 = np.array([7,6,5])
print(mat_1)
print(mat_2)

[2 5 8]
[7 6 5]


In [22]:
print(mat_1.shape,mat_2.shape)

(3,) (3,)


In [25]:
m1 = np.array([[2,4,6],[9,7,5],[11,23,45]])
m1
print(m1.shape)

(3, 3)


# Create matrix with random values

In [26]:
m_ran_1 = np.random.rand(5,5)
print(m_ran_1)

[[0.95640423 0.04086864 0.07578034 0.69272534 0.89298815]
 [0.53091553 0.87140246 0.99970772 0.46572777 0.57694464]
 [0.15696255 0.34742562 0.65605209 0.35289285 0.21242178]
 [0.89626817 0.89950398 0.22033452 0.45600871 0.25078511]
 [0.42617146 0.2210817  0.0658346  0.68799131 0.32168217]]


## Creating matrix all values is 1

In [29]:
mat_one = np.ones((5,5), dtype=int)
print(mat_one)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Zero matrix OR Null Matrix

In [31]:
mat_zer = np.zeros((10,10))
print(mat_zer)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Identity Matrix

In [32]:
mat_ident = np.eye(6,6)
print(mat_ident)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


# Matrix with random integer values

In [34]:
mat_int= np.random.randint(100, size=(5,5))
print(mat_int)

[[14 30 66  1 94]
 [83 65 21 89 19]
 [66 49 62 59 88]
 [57 25 23 70 98]
 [42 75  2 45  5]]


## Transpose of MAtrix

In [37]:
mat_T = np.transpose(mat_int)
print(mat_T)

[[14 83 66 57 42]
 [30 65 49 25 75]
 [66 21 62 23  2]
 [ 1 89 59 70 45]
 [94 19 88 98  5]]
